### ISSUE TITLE
Replay protection

### ISSUE THREAD

**Issue by qwertys318** [broxus/ever-wallet-contract#1]
It was said `Can send up to 4 messages at the same time.`
But when I try to send just 2 transactions I get:
```
507: Message expired. Contract was not executed on chain.
Possible reason: Contract execution was terminated with error: Contract did not accept message, exit code: 52 (Replay protection exception). Try again.
Tip: For more information about exit code check the contract source code or ask the contract developer
```
Am I doing something wrong?

**Comment by Rexagon** [comment]
> 4 messages at the same time

It means that there is a method which can be used to send up to 4 messages in a single transaction. It has nearly the same payload to the `WalletV3`, but with the support of ABI 2.3.

`sendTransactionRaw` doesn't have a strict signature, you can define and use an ABI with all required "instances" of it:
```json
{
  "ABI version": 2,
  "version": "2.3",
  "header": ["pubkey", "time", "expire"],
  "functions": [
    {
      "name": "sendTransactionRaw1",
      "inputs": [
        { "name": "flags", "type": "uint8" },
        { "name": "message", "type": "cell" },
      ],
      "outputs": [],
      "id": "0x169e3e11"
    },
    // ...
    {
      "name": "sendTransactionRaw4",
      "inputs": [
        { "name": "flags1", "type": "uint8" },
        { "name": "message1", "type": "cell" },
        { "name": "flags2", "type": "uint8" },
        { "name": "message2", "type": "cell" },
        { "name": "flags3", "type": "uint8" },
        { "name": "message3", "type": "cell" },
        { "name": "flags4", "type": "uint8" },
        { "name": "message4", "type": "cell" },
      ],
      "outputs": [],
      "id": "0x169e3e11"
    }
  ],
  "data": [],
  "events": [],
}
```

You may ask why is it like this? To simplify the contract and reduce the number of handlers, and it is also simpler to use from the native stuff (just pack these messages with flags into the cell builder after the function id and you are done, proceed to the signature step).

There is an example using `nekoton-wasm` directly (you shouldn't use it directly):
https://github.com/broxus/ever-wallet-contract/blob/master/tests/1-wallet-test.ts#L208-L251

Or if you are using the `ever-sdk`, you can use this - https://github.com/tonlabs/ever-sdk/blob/master/docs/reference/types-and-methods/mod_abi.md#encode_internal_message and pass its result to the `{"name":"message","type":"cell"}`  params.

**Comment by Rexagon** [comment]
The replay protection is the same as in other Solidity contracts. When sending a large number of external messages at once, if the last (by `timestamp`) is accepted first, all previous ones will be rejected with an error `52`.
